### ISSUE TITLE
pcap rejects all packets

### ISSUE THREAD

**Issue by rybushkindmitry** [sip3io/sip3-ansible#6]
Установлена версия 2020.1.1
Captain стартует, но ничего не отправляет

27-09-2020 00:29:30.077 [vert.x-eventloop-thread-3] INFO  i.s.captain.ce.capturing.PcapEngine - Listening network interface: ens18
27-09-2020 00:29:30.209 [pool-2-thread-1] ERROR i.s.captain.ce.capturing.PcapEngine - Got exception...
org.pcap4j.core.PcapNativeException: Error occurred in pcap_compile: expression rejects all packets
        at org.pcap4j.core.PcapHandle.setFilter(PcapHandle.java:482)
        at org.pcap4j.core.PcapHandle.setFilter(PcapHandle.java:508)
        at io.sip3.captain.ce.capturing.PcapEngine.loop(PcapEngine.kt:177)
        at io.sip3.captain.ce.capturing.PcapEngine$online$2.run(PcapEngine.kt:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
27-09-2020 00:29:30.250 [vert.x-eventloop-thread-2] ERROR i.s.commons.vertx.AbstractBootstrap - Vertx 'deployVerticle()' failed. Verticle: class io.sip3.captain.ce.socket.ManagementSocket
io.vertx.core.impl.NoStackTraceThrowable: Verticle deployment failed.Could not be added as child of parent verticle

**Comment by rybushkindmitry** [comment]
problem solved. need to set bpf-filter parameter to "udp or tcp"
